services:
  # Laravel (PHP + Nginx)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel-net
    expose:
      - "9000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
      - MYSQL_DB=laravel
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80" # Laravel App accessible on localhost:8080
    networks:
      - laravel-net
    depends_on:
      - php

  # Database (MariaDB)
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mariaDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-net

  # phpMyAdmin untuk mengelola database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" # phpMyAdmin accessible on localhost:8081
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - laravel-net
    depends_on:
      - db
  # VSCode (Code Server)
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5173:5173"
      - "9000:9000"
      - "5000:5000"
    volumes:
      - "(your path):/home/coder/project"
    environment:
      - PASSWORD=byanbyan
    restart: unless-stopped
    tty: true
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  db_data:
